### PR TITLE
fix(backend:s3): fix passing a client reference, close #18

### LINKED ISSUE #18: AWS S3 custom client injection does not work as expected
The feature introduced in #17 does not work in a real Symfony project.

When using the following configuration, where `aws_s3_client` (or `@aws_s3_client`) is a S3Client reference:
image

The following line does not work:
image

Because in fact it's not a `Reference` but only a string:
image

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tests pass?   | yes    
| Fixed tickets | Close #18   

Passing a service reference for a S3 adapter will now correctly resolves to the service instance.

### CODE REVIEW

File: src/DependencyInjection/CKSourceCKFinderExtension.php [hunk 1]
```diff
@@ -56,10 +58,31 @@ public function load(array $configs, ContainerBuilder $container): void
...
+
+        foreach ($config['connector']['backends'] as $backend) {
+            if($backend['adapter'] === 's3') {
+                if (is_string($clientId = $backend['client'] ?? null)) {
+                    if (null === ($servicesMap[$clientId] ?? null)) {
+                        $servicesMap[$clientId] = new Reference($clientId);
+                    }
+                }
+            }
+        }
```
Comment (Kocal) [inline src/DependencyInjection/CKSourceCKFinderExtension.php:82]: Maybe there is a better way to detect services references... who knows

Comment (Kocal) [reply src/DependencyInjection/CKSourceCKFinderExtension.php]: who knows
